apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: activity-api-1
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: activity-team
  system: activity-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Activity API
      license:
        name: MIT
    servers:
      - url: https://www.boredapi.com/api
    paths:
      /activity:
        get:
          summary: activity
          responses:
            '200':
              description: Successful response
              content:
                application/json:
                  schema:
                    type: object
              examples:
                activity:
                  value:
                    - participants: 1
                      key: 2055368
                      type: charity
                      activity: social-service
    ...
