apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: cat-fact-api
  description: Retrieve cat facts
spec:
  type: openapi
  lifecycle: production
  owner: fact-team
  system: fact-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Fact API
      license:
        name: MIT
    servers:
      - url: https://catfact.ninja/fact
    paths:
      /fact:
        get:
          summary: List all facts
    ...
