apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My existing API component
spec:
  type: openapi
  lifecycle: production
  owner: guests
  system: sample-api
  definition: |
  openapi: "3.0.0"
  info:
    version: 1.0.0
    title: Sample API
    license:
      name: MIT
  servers:
    - url: https://crudcrud.com/api/19188936f5274a9da25de6634279ec6a
  paths:
    /users:
      get:
        summary: Retrieve list of users
  ...
